In [1]:
T = 37 #temperatura em graus celsius

In [2]:
print(T)

37


In [3]:
T

37

In [4]:
type(T)

int

In [5]:
V = 180

In [6]:
V

180

In [7]:
print(V)

180


In [8]:
type(V)

int

In [9]:
pi = 3.14

In [10]:
type(pi)

float

In [11]:
import numpy as np

In [12]:
u = [1, 2]
v = [2, 1]

In [13]:
u + v

[1, 2, 2, 1]

In [14]:
u = np.array(u)

In [15]:
v = np.array(v)

In [16]:
#soma vetorial
u + v

array([3, 3])

In [17]:
#subtração de vetores
u - v

array([-1,  1])

In [18]:
#subtração de vetores II

In [19]:
v - u

array([ 1, -1])

In [20]:
#produto escalar e modulo
a = np.array([2, 3])
b = np.array([4, -1])

In [21]:
u*v

array([2, 2])

In [22]:
a*b

array([ 8, -3])

In [23]:
#acima é o produto elemento a elemento dos vetores

In [24]:
#produto interno ou produto escalar
a.dot(b)

5

In [25]:
#calculando o modulo
mod_a = np.linalg.norm(a)

In [26]:
mod_a

3.605551275463989

In [27]:
mob_b = np.linalg.norm(b)
print(mod_b)

NameError: name 'mod_b' is not defined

In [28]:
mod_b = np.linalg.norm(b)
print(mod_b)

4.123105625617661
